# Project: tetris
# Makefile created by Dev-C++ 5.5.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../../obj/exception.o ../../obj/genlib.o ../../obj/graphics.o ../../obj/random.o ../../obj/simpio.o ../../obj/strlib.o ../../obj/imgui.o ../../obj/fileIO.o ../../obj/flow.o ../../obj/interact.o ../../obj/layout.o ../../obj/main.o ../../obj/tetris.o
LINKOBJ  = ../../obj/exception.o ../../obj/genlib.o ../../obj/graphics.o ../../obj/random.o ../../obj/simpio.o ../../obj/strlib.o ../../obj/imgui.o ../../obj/fileIO.o ../../obj/flow.o ../../obj/interact.o ../../obj/layout.o ../../obj/main.o ../../obj/tetris.o
LIBS     = -L"C:/Program Files/Dev-Cpp/MinGW32/lib" -L"C:/Program Files/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc -mwindows -g3
INCS     = -I"C:/Program Files/Dev-Cpp/MinGW32/include" -I"../../lib/libgraphics" -I"../../lib/simpleGUI"
CXXINCS  = -I"C:/Program Files/Dev-Cpp/MinGW32/include" -I"C:/Program Files/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.7.2/include/c++" -I"../../lib/libgraphics" -I"../../lib/simpleGUI"
BIN      = ../../tetris.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

../../obj/exception.o: ../../lib/libgraphics/exception.c
	$(CC) -c ../../lib/libgraphics/exception.c -o ../../obj/exception.o $(CFLAGS)

../../obj/genlib.o: ../../lib/libgraphics/genlib.c
	$(CC) -c ../../lib/libgraphics/genlib.c -o ../../obj/genlib.o $(CFLAGS)

../../obj/graphics.o: ../../lib/libgraphics/graphics.c
	$(CC) -c ../../lib/libgraphics/graphics.c -o ../../obj/graphics.o $(CFLAGS)

../../obj/random.o: ../../lib/libgraphics/random.c
	$(CC) -c ../../lib/libgraphics/random.c -o ../../obj/random.o $(CFLAGS)

../../obj/simpio.o: ../../lib/libgraphics/simpio.c
	$(CC) -c ../../lib/libgraphics/simpio.c -o ../../obj/simpio.o $(CFLAGS)

../../obj/strlib.o: ../../lib/libgraphics/strlib.c
	$(CC) -c ../../lib/libgraphics/strlib.c -o ../../obj/strlib.o $(CFLAGS)

../../obj/imgui.o: ../../lib/simpleGUI/imgui.c
	$(CC) -c ../../lib/simpleGUI/imgui.c -o ../../obj/imgui.o $(CFLAGS)

../../obj/fileIO.o: ../../fileIO.c
	$(CC) -c ../../fileIO.c -o ../../obj/fileIO.o $(CFLAGS)

../../obj/flow.o: ../../flow.c
	$(CC) -c ../../flow.c -o ../../obj/flow.o $(CFLAGS)

../../obj/interact.o: ../../interact.c
	$(CC) -c ../../interact.c -o ../../obj/interact.o $(CFLAGS)

../../obj/layout.o: ../../layout.c
	$(CC) -c ../../layout.c -o ../../obj/layout.o $(CFLAGS)

../../obj/main.o: ../../main.c
	$(CC) -c ../../main.c -o ../../obj/main.o $(CFLAGS)

../../obj/tetris.o: ../../tetris.c
	$(CC) -c ../../tetris.c -o ../../obj/tetris.o $(CFLAGS)
